In [1]:
name = input(" Who are you? ")
print("\tWelcome",name)

 Who are you? Akash
	Welcome Akash


In [ ]:
x = 5
if x > 2 :
  print(" Bigger than 2 ")
  print(" Still Bigger ")
print(" Done with 2 ")

for i in range(5):
  print(i)
  if i > 2:
    print(" Bigger than 2 ")
  print(" Done with i ",i)
print(" All Done ")

 Bigger than 2 
 Still Bigger 
 Done with 2 
0
 Done with i  0
1
 Done with i  1
2
 Done with i  2
3
 Bigger than 2 
 Done with i  3
4
 Bigger than 2 
 Done with i  4
 All Done 


In [ ]:
x = 4
if x > 2:
  print(" Bigger ")
else:
  print(" Not Bigger ")
print(" All Done ")

 Bigger 
 All Done 


In [ ]:
x=11
if x<2:
  print("Small")
elif x<10:
  print("Medium")
else:
  print("Large")

Large


In [18]:
astr= 'Hello Bob'
istr= list(astr)
print(" First ",istr)

 First  ['H', 'e', 'l', 'l', 'o', ' ', 'B', 'o', 'b']


In [17]:
astr='123'
istr= list(astr)
print(" Second ",istr)

 Second  ['1', '2', '3']


In [ ]:
astr= 'Hello Bob'
try:
  istr= int(astr)
except:
  istr=-1
print("First",istr)

astr='123'
try:
  istr= int(astr)
except:
  istr=-1
print("Second",istr)

First -1
Second 123


In [ ]:
astr='Bob'

try:
  print(" Hello")
  istr=int(astr)
  print("There")
except:
  istr=-1
print(" Done ",istr)

 Hello
 Done  -1


In [ ]:
def mul(a,b):
  return a*b

a=5
b=10
c=mul(a,b)
print(" Product : ",c)


 Product :  50


In [ ]:
big= max("Helloworld")
print(big)

tiny= min("Helloworld")
print(tiny)

w
H


In [ ]:
for i in [5,4,3,2,1] :
  print(i)

5
4
3
2
1


In [ ]:
smallest = None
print("Before : \n")
for value in [3,41,12,9,74,15]:
  if smallest is None:
    smallest= value
  elif value < smallest :
    smallest =value
  print('Smallest : ',value)

print('\nAfter : ',smallest)

Before : 

Smallest 3
Smallest 41
Smallest 12
Smallest 9
Smallest 74
Smallest 15

After :  3


In [ ]:
smallest = None
print(" Before : \n")
for value in [3,41,12,9,74,15]:
  if smallest is not None:
    smallest= value
  elif value != smallest :
    smallest =value
  print(' Smallest : ',value)

print('\nAfter : ',smallest)

 Before : 

 Smallest :  3
 Smallest :  41
 Smallest :  12
 Smallest :  9
 Smallest :  74
 Smallest :  15

After :  15


In [ ]:
def sal(a,b):
  return a*b

h=float(input(" Enter Hours "))
r=float(input(" Enter Rate per Hour "))

s=sal(h,r)

print(" Gross Pay : ",s)

 Enter Hours 30
 Enter Rate per Hour 2
 Gross Pay :  60.0


In [ ]:
x=int(input("Enter value of x "))
if x<2:
  print(" Below 2 ")
elif x>=2:
  print(" 2 or more ")
else:
  print(" Something Else ")

"""
x=int(input("Enter value of x "))
if x<2:
  print(" Below 2 ")
elif x<20:
  print(" Below 20 ")
elif x<10:
  print(" Below 10 ")
else:
  print("Something else")      """


Enter value of x 1
 Below 2 


'\nif x<2:\n  print(" Below 2 ")\nelif x<20:\n  print(" Below 20 ")\nelif x<10:\n  print(" Below 10 ")  \nelse:\n  print("Something else")      '

In [ ]:
def sal(a,b,c=None):
  if(c==None):
    return a*b
  else:
    return a*b*c

h=float(input(" Enter Hours "))
r=float(input(" Enter Rate per Hour "))
hh=float(input(" Enter Additional Hours "))
#if(isdigit(h) and isdigit(r)):
s=sal(h,r)
ss=sal(h,r,hh)

print(" Gross Pay : ",s)
print(" Gross Pay with Additional Hours: ",ss)

 Enter Hours 50
 Enter Rate per Hour 10
 Enter Additional Hours 2
 Gross Pay :  500.0
 Gross Pay :  1000.0


In [ ]:
#0 is equal to 0 | Infinite Loop
n=0
while n>0:
  print(" Lather ")
  print(" Rinse ")
print(" Dry Clean")

 Dry Clean


In [ ]:
largest_so_far = -1
print("Before : ",largest_so_far)
for the_num in  [9,41,12,3,74,15]:
  if the_num>largest_so_far:
    largest_so_far=the_num
  print(largest_so_far,the_num)
print("After : ",largest_so_far)

Before  -1
9 9
41 41
41 12
41 3
74 74
74 15
After  74


In [ ]:
smallest_so_far = 80
print("Before : ",smallest_so_far)
for the_num in  [9,41,12,3,74,15]:
  if the_num<smallest_so_far:
    smallest_so_far=the_num
  print(smallest_so_far,the_num)
print("After : ",smallest_so_far)

Before :  80
9 9
9 41
9 12
3 3
3 74
3 15
After :  3


In [19]:
#scipy
import scipy
print(" scipy : %s"% scipy.__version__)

 scipy : 1.11.3


In [20]:
#pandas
import pandas
print(" pandas : %s"% pandas.__version__)

 pandas : 1.5.3


In [21]:
#numpy
import numpy
print(" numpy : %s"% numpy.__version__)

 numpy : 1.23.5


In [22]:
#statsmodels
import statsmodels
print(" statsmodels : %s"% statsmodels.__version__)

 statsmodels : 0.14.0


In [23]:
#sklearn
import sklearn
print(" sklearn : %s"% sklearn.__version__)

 sklearn : 1.2.2


In [26]:
#Adding Numbers
def add_numbers(x,y):
  return x+y
a=15;b=1;
add_numbers(a,b)

16

In [27]:
#None keyword
def add_numbers(x,y,z=None):
  if(z==None):
    return x+y
  else:
    return x+y+z
add_numbers(30,3)

33

In [29]:
print(add_numbers(20,3,7))

30


In [32]:
#Flags
def add_numbers(x,y,z=None,flag=False):
  if(flag):
    print('Flag is ON!')
  if(z==None):
    return x+y
  else:
    return x+y+z
print(add_numbers(10,20,25,flag=True))

Flag is ON!
55


In [34]:
#flags
def add_numbers(x,y,z=None,flag=False):
  if(flag):
    print('flag is on!')
  if(z==None):
    return x+y
  else:
    return x+y+z
print(add_numbers(10,20,30,flag=False))

60


In [35]:
#varible
def add_numbers(x,y):
  return x+y
  a=add_numbers
a=15;b=5;
add_numbers(a,b)

20

In [24]:
#tuples() - Immutable

x = (1,'a',2,'b',1.2)
type(x)

tuple

#x.append(3.3) -> Can't Append in Tuples
print(x)

(1, 'a', 2, 'b', 1.2)


In [ ]:
#list

x = [1,'a',2,'b',1.2]
type(x)

list

x.append(3.3)
print(x)

[1, 'a', 2, 'b', 1.2, 3.3]


In [ ]:
#list[] - Mutable
x = [1,'a',2,'b',1.2]
type(x)

list

for item in x:
  print(item)

1
a
2
b
1.2


In [ ]:
len(x)

5

In [ ]:
#Repeat a list into * times
[1,2,3]*2

[1, 2, 3, 1, 2, 3]

In [ ]:
#Concatination
[1,2,3] + [4,5]

[1, 2, 3, 4, 5]

In [ ]:
#Check weather an objects is present list
27 in [16, 27, 31, 44, 57]

False

In [ ]:
x= 'This is a string'

In [ ]:
print(x[0]) #Prints First char

T


In [ ]:
print(x[0:3])   #Start from 0 | Stop before 3

Thi


In [ ]:
print(x[-4:-2])

ri


In [ ]:
print(x[:-2])

This is a stri


In [ ]:
print(x[3:])

s is a string


In [36]:
FN="Akash"
MN="G S"
LN="Kumar"
print(FN+" "+MN+" "+LN)

Akash G S Kumar


In [37]:
FN="Akash is going to college".split(' ')[0]
MN="Akash GS is going to college".split(' ')[1]
LN="Hello Kumar".split(' ')[-1]

print(FN+" "+MN+" "+LN)

Akash GS Kumar


In [38]:
print(LN)

Kumar


In [39]:
print(FN+' '+MN)

Akash GS


In [ ]:
#"CHRIS" + "2" -> Works same | Use " " else ERROR
"CHRIS" + str(2)


'CHRIS2'

In [41]:
#Dictionaaries{}

x = {"Akash":"akash@gmail.com","Varun":"varun@gmail.com"}

x["Varun"] #Retrieve value by using Indexing Operation

'varun@gmail.com'

In [40]:
{'Akash' : 'akash@gmail.com','Bill' : 'bill@gmail.com'}

{'Akash': 'akash@gmail.com', 'Bill': 'bill@gmail.com'}

In [43]:
#Add Dictionaries
x = {
    'Akash' : 'akash@gmail.com',
    'Thomp': 'mit@ua.edu'
  }

x['Roman']='roman@gmail.com'

In [44]:
print(x)

{'Akash': 'akash@gmail.com', 'Thomp': 'mit@ua.edu', 'Roman': 'roman@gmail.com'}


In [45]:
#remove dictionaries
x.pop('Akash')
print('dict',x)

dict {'Thomp': 'mit@ua.edu', 'Roman': 'roman@gmail.com'}


In [46]:
#iterate over all items of list

for name in x.items():
  print(name)

('Thomp', 'mit@ua.edu')
('Roman', 'roman@gmail.com')


In [50]:
#iterate all names
for name in x:
  print(name)

Thomp
Roman


In [49]:
#iterate over all of the value
for email in x.values():
  print(email)

mit@ua.edu
roman@gmail.com


In [57]:
#you can unpack a sequence into different variables
x=('Akash','GS','akash@gmail.com')

In [58]:
x

('Akash', 'GS', 'akash@gmail.com')

In [63]:
#make sure the number of values you are unpacking matches the number of variables be
x=('Akash','Kumar','akash@gmail.com','Udupi')
fname,lname,email,cname = x


In [64]:
x

('Akash', 'Kumar', 'akash@gmail.com', 'Udupi')

In [65]:
#python has a built in method for convenient atring formatting

sales_record = {
    'price':3.24,
    'num_items':4,
    'person':'Akash',
    'email':'akash@gmail.com'
}

In [66]:
sales_statement = '{} bought {} items(s) at a price of INR {} each for a Total INR {}'

In [67]:
print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

Akash bought 4 items(s) at a price of INR 3.24 each for a Total INR 12.96


In [68]:
import datetime as dt
import time as tm

In [69]:
tm.time()

1700016858.0184476

In [70]:
from datetime import date
from datetime import time
from datetime import datetime

today=date.today()
print('Todays date is',today)

Todays date is 2023-11-15


In [71]:
#convert the timestamp to datetime
dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2023, 11, 15, 2, 54, 23, 321591)

In [72]:
#Handy datetime attributes

dtnow.year, dtnow.month,dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2023, 11, 15, 2, 54, 23)

In [75]:
#timedelta is a duration expressing the difference between two dates
delta=dt.timedelta(days = 100) # create a TimeTable of 100 days

In [76]:
#date.today returns the current local date
today=dt.date.today()

In [79]:
#Date 100 days ago
today-delta

datetime.date(2023, 8, 7)

In [80]:
#Comparing dates
today > today-delta

True

In [81]:
class person:
  institute = "MSIS, Manipal"
  def set_name(self,new_name):
    self.name=new_name
  def set_location(self,new_location):
    self.name=new_location

In [82]:
person=person()
person.set_name('Akash')
person.set_location('udupi')

In [84]:
x={1,'x',2,'y',(1,2,3),'hello'}
type(x)

set

In [85]:
y=(1,2,3)
type(y)

tuple

In [86]:
x={1,'x',2,'y',3}
z={1,'x',2,'y','a'}
print(x,z)

{1, 2, 3, 'y', 'x'} {1, 2, 'a', 'y', 'x'}


In [88]:
#Add value to the set
z.add('a')
print(y,z)

(1, 2, 3) {1, 2, 'a', 'y', 'x'}


In [89]:
x=[1,'x',2,'y']
type(x)

list

In [90]:
x

[1, 'x', 2, 'y']

In [91]:
store1=[10.00,11.00,12.34,5.34]
store2=[19.00,10.10,12.34,5.01]
store3=[15.00,12.00,11.00,6.00]
cheapest=map(min,store1,store2,store3)
costly=map(max,store1,store2,store3)
print(cheapest)
print(costly)

In [92]:
for item in cheapest:
  print(item)

10.0
10.1
11.0
5.01


In [93]:
for item in costly:
  print(item)

19.0
12.0
12.34
6.0


In [94]:
def calculateSquare(a):
  return a*a

In [95]:
numbers = (1,2,3,4)
res=map(calculateSquare,numbers)
print(res)

In [96]:
res= list(res)

In [97]:
print(res)

[1, 4, 9, 16]


In [98]:
for item in res:
  print(item)

1
4
9
16


In [ ]:
numbers=(1,2,3,4)
res=map(lambda x: x*x,numbers)
print(res)

In [ ]:
num1=[4,5,6]
num2=[5,6,7]

In [ ]:
res=map(lambda n1,n2: n1+n2,num1,num2)
list(res)

[9, 11, 13]

In [ ]:
people = ['Python Progamming Language', 'Computer Lab Test','Vinod Scored A','Kumar Scored B']
def split_title_and_name(person):
  title=person.split()[0]
  lastname=person.split()[-1]
  return '{} {}'.format(title,lastname)
list(map(split_title_and_name,people))

['Python Language', 'Computer Test', 'Vinod A', 'Kumar B']

In [ ]:
# Iterate from 0 to 200 and return the odd numbers

odd_numbers = [num for num in range(1, 201, 2)]
print(odd_numbers)


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199]


In [ ]:
for num in range(1,201):
  if num%2 != 0:
    print(num)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101
103
105
107
109
111
113
115
117
119
121
123
125
127
129
131
133
135
137
139
141
143
145
147
149
151
153
155
157
159
161
163
165
167
169
171
173
175
177
179
181
183
185
187
189
191
193
195
197
199


In [ ]:
import numpy as np
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
x=np.matrix([[1, 2, 3,
              4, 5, 6,
              7, 8, 9]])

print(np.diag(x))

[1]


In [ ]:
import pandas as pd
s=pd.Series()
print(s)

Series([], dtype: float64)


<ipython-input-14-36194efe155a>:2: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s=pd.Series()


In [ ]:
import pandas as pd
import numpy as np

data = np.array(['a','b','c','d'])
s=pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [ ]:
import pandas as pd
import numpy as np

data = np.array(['a','b','c','d'])
s=pd.Series(data,index=[100,101,102,103])
print(s)

100    a
101    b
102    c
103    d
dtype: object


In [ ]:
import pandas as pd
import numpy as np

data = {'a' : 0., 'b' : 1, 'c' : 2.}
s=pd.Series(data,index=['b','c','d','a'])
print(s)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In [ ]:
import pandas as pd
import numpy as np

data = {'a' : 0., 'b' : 1, 'c' : 2.}
s=pd.Series(5,index=['b','c','d','a'])
print(s)

In [103]:
import numpy as np
p = np.ones([3, 3], dtype=float)
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [104]:
np.vstack([p,2*p])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [105]:
np.hstack([p,2*p])

array([[1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.],
       [1., 1., 1., 2., 2., 2.]])

In [99]:
#Program to double each item in a list using map()
numbers = [1, 2, 3, 4, 5]

double = lambda x: x * 2
doubled_numbers = map(double, numbers)
doubled_numbers_list = list(doubled_numbers)

print(doubled_numbers_list)

[2, 4, 6, 8, 10]


In [107]:
#Define a lambda function with three parameters. But only use the First two
my_lambda = lambda x, y, z: x + y
result = my_lambda(10, 20, 30)

print(result)

30


In [110]:
#Importing the pandas library and Aliasing as pd
import pandas as pd
import numpy as np
data=np.array(['a','b','c','d'])
s=pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


In [111]:
import pandas as pd
import numpy as np
data={'1b':1,'a1':0,'c':2}
s=pd.Series(data)
print(s)

1b    1
a1    0
c     2
dtype: int64


In [112]:
import pandas as pd
import numpy as np
data={'a':0,'b':1,'c':2}
s=pd.Series(data,index=['b','c','d','a'])
print(s)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


In [113]:
import pandas as pd
import numpy as np
s=pd.Series(5,index=[0,1,2,3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64


In [117]:
#retrive the Fourth element
import pandas as pd
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s[3])

4


In [116]:
#Retrive the First three element
print(s[:3])

a    1
b    2
c    3
dtype: int64


In [118]:
print(s[-3:])

c    3
d    4
e    5
dtype: int64


In [119]:
print(s['a'])

1


In [120]:
print(s[-5:1])

a    1
dtype: int64


In [121]:
print(s[-5])

1


In [122]:
print(s[['a','c','d']])

a    1
c    3
d    4
dtype: int64


In [123]:
import numpy as np
old = np.array([[1,1,1],[1,1,1]])
new=old
new[0:2,0:2]=0
print(new)

[[0 0 1]
 [0 0 1]]


In [124]:
import pandas as pd
animals=['Tiger','Lion','Horse']
pd.Series(animals)

0    Tiger
1     Lion
2    Horse
dtype: object

In [125]:
numbers=[1,2,3]
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [126]:
animals=['Tiger','Lion',None]
pd.Series(animals)

0    Tiger
1     Lion
2     None
dtype: object

In [127]:
numbers=[1,2,None]
pd.Series(numbers)

0    1.0
1    2.0
2    NaN
dtype: float64

In [128]:
import numpy as np
np.nan == None

False

In [131]:
#nan is similar to None. But it is a numeric value which is not comparable directly
np.nan == np.nan

False

In [130]:
np.isnan(np.nan)

True

In [ ]:
sports = { 'Cricket' : 'India',
           'Golf' : 'Scotland',
           'Sumo' : 'Japan',
           'Taekwonda' : 'South Korean'}

s = pd.Series(sports)
s

Cricket             India
Golf             Scotland
Sumo                Japan
Taekwonda    South Korean
dtype: object

In [ ]:
s.iloc[3]

'South Korean'

In [ ]:
s['Sumo']

'Japan'

In [ ]:
sports = { 99 : 'India',
           100 : 'Scotland',
           101 : 'Japan',
           102 : 'South Korean'}

s = pd.Series(sports)


In [ ]:
s[101]

'Japan'

In [ ]:
s=pd.Series(np.random.randint(0,1000,10000))
s.head()

0    642
1    592
2    884
3    897
4    262
dtype: int64

In [ ]:
len(s)

10000

In [ ]:
import pandas as pd

purchase_1=pd.Series({'Name' : 'Chris',
                        'item Purchased' : 'Milk',
                        'cost':22.50})
purchase_2=pd.Series({'Name' : 'Kavin',
                        'item Purchased' : 'Coffee',
                        'cost':12.50})
purchase_3=pd.Series({'Name' : 'Sam',
                        'item Purchased' : 'Sugar',
                        'cost':10.50})

df=pd.DataFrame([purchase_1,purchase_2,purchase_3],
                   index=['store 1','store 1','store 2'])
df.head()

Name item Purchased  cost
store 1  Chris           Milk  22.5
store 1  Kavin         Coffee  12.5
store 2    Sam          Sugar  10.5

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_0, *['cost'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_1, *['cost'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_2, *['Name'], **{})
chart

import numpy as np
from google.colab import autoviz

def categorical_histogram(df, colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  df.groupby(colname).size().plot(kind='barh', color=sns.palettes.mpl_palette(mpl_palette_name), figsize=(8*figscale, 4.8*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  return autoviz.MplChart.from_current_mpl_state()

chart = categorical_histogram(_df_3, *['item Purchased'], **{})
chart

import numpy as np
from google.colab import autoviz

def heatmap(df, x_colname, y_colname, figscale=1, mpl_palette_name='viridis'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  import pandas as pd
  plt.subplots(figsize=(8 * figscale, 8 * figscale))
  df_2dhist = pd.DataFrame({
      x_label: grp[y_colname].value_counts()
      for x_label, grp in df.groupby(x_colname)
  })
  sns.heatmap(df_2dhist, cmap=mpl_palette_name)
  plt.xlabel(x_colname)
  plt.ylabel(y_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = heatmap(_df_4, *['Name', 'item Purchased'], **{})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_5, *['cost', 'Name'], **{'inner': 'stick'})
chart

import numpy as np
from google.colab import autoviz

def violin_plot(df, value_colname, facet_colname, figscale=1, mpl_palette_name='Dark2', **kwargs):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (12 * figscale, 1.2 * figscale * len(df[facet_colname].unique()))
  plt.figure(figsize=figsize)
  sns.violinplot(df, x=value_colname, y=facet_colname, palette=mpl_palette_name, **kwargs)
  sns.despine(top=True, right=True, bottom=True, left=True)
  return autoviz.MplChart.from_current_mpl_state()

chart = violin_plot(_df_6, *['cost', 'item Purchased'], **{'inner': 'stick'})
chart