In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Importing Dataset
data = pd.read_csv("D:\MSIS\FML Lab\Part 1\Dataset\Data.csv")

In [3]:
data.describe(include="all")

Country        Age        Salary Purchased
count       10   9.000000      9.000000        10
unique       3        NaN           NaN         2
top     France        NaN           NaN        No
freq         4        NaN           NaN         5
mean       NaN  38.777778  63777.777778       NaN
std        NaN   7.693793  12265.579662       NaN
min        NaN  27.000000  48000.000000       NaN
25%        NaN  35.000000  54000.000000       NaN
50%        NaN  38.000000  61000.000000       NaN
75%        NaN  44.000000  72000.000000       NaN
max        NaN  50.000000  83000.000000       NaN

In [4]:
data.info

<bound method DataFrame.info of    Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes>

In [5]:
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [6]:
#One-Hot Encoding for column named Country
data1=pd.get_dummies(data,columns=["Country"])

In [7]:
data1

Age   Salary Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0        No            True            False          False
1  27.0  48000.0       Yes           False            False           True
2  30.0  54000.0        No           False             True          False
3  38.0  61000.0        No           False            False           True
4  40.0      NaN       Yes           False             True          False
5  35.0  58000.0       Yes            True            False          False
6   NaN  52000.0        No           False            False           True
7  48.0  79000.0       Yes            True            False          False
8  50.0  83000.0        No           False             True          False
9  37.0  67000.0       Yes            True            False          False

In [8]:
data2=data1.copy()

In [9]:
#Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data2["Purchased"]=le.fit_transform(data1["Purchased"])
data2["Country_France"]=le.fit_transform(data1["Country_France"])
data2["Country_Germany"]=le.fit_transform(data1["Country_Germany"])
data2["Country_Spain"]=le.fit_transform(data1["Country_Spain"])

In [10]:
data2

Age   Salary  Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0          0               1                0              0
1  27.0  48000.0          1               0                0              1
2  30.0  54000.0          0               0                1              0
3  38.0  61000.0          0               0                0              1
4  40.0      NaN          1               0                1              0
5  35.0  58000.0          1               1                0              0
6   NaN  52000.0          0               0                0              1
7  48.0  79000.0          1               1                0              0
8  50.0  83000.0          0               0                1              0
9  37.0  67000.0          1               1                0              0

In [11]:
#Finding null values
data2.isnull().sum()

Age                1
Salary             1
Purchased          0
Country_France     0
Country_Germany    0
Country_Spain      0
dtype: int64

In [12]:
data2["Age"].fillna(data2["Age"].mode(),inplace=True)
data2["Salary"].fillna(data2["Salary"].mean(),inplace=True)

In [13]:
data2

Age        Salary  Purchased  Country_France  Country_Germany   
0  44.0  72000.000000          0               1                0  \
1  27.0  48000.000000          1               0                0   
2  30.0  54000.000000          0               0                1   
3  38.0  61000.000000          0               0                0   
4  40.0  63777.777778          1               0                1   
5  35.0  58000.000000          1               1                0   
6  44.0  52000.000000          0               0                0   
7  48.0  79000.000000          1               1                0   
8  50.0  83000.000000          0               0                1   
9  37.0  67000.000000          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

In [14]:
#Cross Check NULL values
data2.isnull().sum()

Age                0
Salary             0
Purchased          0
Country_France     0
Country_Germany    0
Country_Spain      0
dtype: int64

In [15]:
#Selecting required columns
X = data2.iloc[:,[0,1]].values
y = data2.iloc[:,3].values

In [16]:
X

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [4.40000000e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [17]:
y

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 1], dtype=int64)

In [18]:
#Splitting Dataset into Training and Testing
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [19]:
X_train

array([[3.7e+01, 6.7e+04],
       [2.7e+01, 4.8e+04],
       [4.4e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [3.8e+01, 6.1e+04],
       [4.4e+01, 7.2e+04],
       [3.5e+01, 5.8e+04]])

In [20]:
X_test

array([[3.00000000e+01, 5.40000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [4.00000000e+01, 6.37777778e+04]])

In [21]:
#Scaling Values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [22]:
X_train

array([[-0.30756234,  0.44897083],
       [-1.84537406, -1.41706417],
       [ 0.76890586, -1.0242147 ],
       [ 1.38403054,  1.62751925],
       [-0.15378117, -0.14030338],
       [ 0.76890586,  0.94003267],
       [-0.61512469, -0.43494049]])

In [23]:
X_test

array([[-1.38403054, -0.82778996],
       [ 1.69159288,  2.02036872],
       [ 0.15378117,  0.13250875]])

In [24]:
#Implementing Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion="entropy",max_depth=5,random_state=0)
DT.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=0)

In [25]:
y_pred = DT.predict(X_test)
y_pred

array([0, 1, 0], dtype=int64)

In [26]:
y_test

array([0, 0, 0], dtype=int64)

In [27]:
#Accuracy of the Model
from sklearn import metrics
prediction=metrics.accuracy_score(y_test,y_pred)
print("Accuracy :",prediction*100,'%')

Accuracy : 66.66666666666666 %
