In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv(r"D:\MSIS\FML Lab\Part 1\Dataset\bestsellers_with_categories.csv")

In [3]:
data

Name   
0                        10-Day Green Smoothie Cleanse  \
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [4]:
#Check for NULL values
data.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [5]:
#Select Columns
x=data.iloc[:,2:5].values
y=data.iloc[:,6].values

In [6]:
#Splitting Dataset into Training and Testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [7]:
#Standard Scalar
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [8]:
#Applying PCA to reduce no. of columns
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance=pca.explained_variance_ratio_
explained_variance

array([0.37995199, 0.3399699 ])

In [9]:
#Implementing RandomForest Model
from sklearn.ensemble import RandomForestClassifier
RClassifier = RandomForestClassifier(n_estimators=30,criterion='entropy',random_state=0)
RClassifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=30, random_state=0)

In [10]:
y_pred_RF = RClassifier.predict(X_test)

In [11]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_RF)
cm

array([[34, 16],
       [ 7, 53]], dtype=int64)

In [21]:
#Accuracy of the Model
from sklearn import metrics
prediction=metrics.accuracy_score(y_test,y_pred_RF)
print("Accuracy :",prediction*100,"%")

Accuracy : 79.0909090909091 %


In [22]:
#Implementing KNN Model
from sklearn.neighbors import KNeighborsClassifier
KClassifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
KClassifier.fit(X_train,y_train)

KNeighborsClassifier()

In [23]:
y_pred_KNN = KClassifier.predict(X_test)

In [24]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_RF)
cm

array([[34, 16],
       [ 7, 53]], dtype=int64)

In [25]:
#Accuracy of the Model
from sklearn import metrics
prediction=metrics.accuracy_score(y_test,y_pred_KNN)
print("Accuracy : ",prediction*100,"%")

Accuracy :  74.54545454545455 %


In [26]:
#Implementing LogesticRegression Model
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [27]:
y_pred=classifier.predict(X_test)

In [28]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[22, 28],
       [11, 49]], dtype=int64)

In [29]:
#Accuracy of the Model
from sklearn import metrics
prediction=metrics.accuracy_score(y_test,y_pred)
print("Accuracy : ",prediction*100,"%")

Accuracy :  64.54545454545455 %
